name: Release Helm Chart

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.5.0
        with:
          name: kanidm
          repository: ${{ github.repository }}/charts
          tag: ${{ steps.version.outputs.VERSION }}
          path: .
          registry: ghcr.io
          registry_username: ${{ github.repository_owner }}
          registry_password: ${{ github.token }}
